# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_axi_apb_bridge_0_2/Final_Project_axi_apb_bridge_0_2.xci
# IP: The module: 'Final_Project_axi_apb_bridge_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_apb_bridge_0_2/Final_Project_axi_apb_bridge_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_axi_apb_bridge_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/Final_Project/Final_Project.srcs/sources_1/bd/Final_Project/ip/Final_Project_axi_apb_bridge_0_2/Final_Project_axi_apb_bridge_0_2.xci
# IP: The module: 'Final_Project_axi_apb_bridge_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/ip/Final_Project_axi_apb_bridge_0_2/Final_Project_axi_apb_bridge_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Project_axi_apb_bridge_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
