# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PS_Block/PS_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block || ORIG_REF_NAME==PS_Block} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_processing_system7_0_0/PS_Block_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_processing_system7_0_0 || ORIG_REF_NAME==PS_Block_processing_system7_0_0} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_axi_gpio_0_0 || ORIG_REF_NAME==PS_Block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_ps7_0_axi_periph_1/PS_Block_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_ps7_0_axi_periph_1 || ORIG_REF_NAME==PS_Block_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_rst_ps7_0_100M_1/PS_Block_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_rst_ps7_0_100M_1 || ORIG_REF_NAME==PS_Block_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_xbar_0/PS_Block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_xbar_0 || ORIG_REF_NAME==PS_Block_xbar_0} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_axi_gpio_1_0/PS_Block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_axi_gpio_1_0 || ORIG_REF_NAME==PS_Block_axi_gpio_1_0} -quiet] -quiet

# IP: bd/PS_Block/ip/PS_Block_auto_pc_0/PS_Block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_Block_auto_pc_0 || ORIG_REF_NAME==PS_Block_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/PS_Block_ooc.xdc
