# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/middle_project.xdc

# Block Designs: bd/middle_project/middle_project.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project || ORIG_REF_NAME==middle_project} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_processing_system7_0_0/middle_project_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_processing_system7_0_0 || ORIG_REF_NAME==middle_project_processing_system7_0_0} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_axi_gpio_1_0/middle_project_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_axi_gpio_1_0 || ORIG_REF_NAME==middle_project_axi_gpio_1_0} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_xbar_0/middle_project_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_xbar_0 || ORIG_REF_NAME==middle_project_xbar_0} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_ps7_0_axi_periph_0/middle_project_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_ps7_0_axi_periph_0 || ORIG_REF_NAME==middle_project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_rst_ps7_0_100M_0/middle_project_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_rst_ps7_0_100M_0 || ORIG_REF_NAME==middle_project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_axi_gpio_0_1/middle_project_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_axi_gpio_0_1 || ORIG_REF_NAME==middle_project_axi_gpio_0_1} -quiet] -quiet

# IP: bd/middle_project/ip/middle_project_auto_pc_0/middle_project_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==middle_project_auto_pc_0 || ORIG_REF_NAME==middle_project_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/middle_project/middle_project.gen/sources_1/bd/middle_project/middle_project_ooc.xdc
