# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/week10_1.xdc

# Block Designs: bd/week10_1/week10_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1 || ORIG_REF_NAME==week10_1} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_processing_system7_0_0/week10_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_processing_system7_0_0 || ORIG_REF_NAME==week10_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_xbar_0/week10_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_xbar_0 || ORIG_REF_NAME==week10_1_xbar_0} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_ps7_0_axi_periph_1/week10_1_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==week10_1_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_rst_ps7_0_100M_1/week10_1_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==week10_1_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_axi_gpio_0_0/week10_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_axi_gpio_0_0 || ORIG_REF_NAME==week10_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_axi_apb_bridge_0_0/week10_1_axi_apb_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_axi_apb_bridge_0_0 || ORIG_REF_NAME==week10_1_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/week10_1/ip/week10_1_auto_pc_0/week10_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_1_auto_pc_0 || ORIG_REF_NAME==week10_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week10_1/week10_1.gen/sources_1/bd/week10_1/week10_1_ooc.xdc
