# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/week4/week4.srcs/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0.xci
# IP: The module: 'GPIO3_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/week4/week4.srcs/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0.xci
# IP: The module: 'GPIO3_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'GPIO3_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
