# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/week10.xdc

# Block Designs: bd/week10/week10.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10 || ORIG_REF_NAME==week10} -quiet] -quiet

# IP: bd/week10/ip/week10_processing_system7_0_1/week10_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_processing_system7_0_1 || ORIG_REF_NAME==week10_processing_system7_0_1} -quiet] -quiet

# IP: bd/week10/ip/week10_ps7_0_axi_periph_0/week10_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_ps7_0_axi_periph_0 || ORIG_REF_NAME==week10_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/week10/ip/week10_rst_ps7_0_100M_0/week10_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_rst_ps7_0_100M_0 || ORIG_REF_NAME==week10_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/week10/ip/week10_axi_apb_bridge_0_1/week10_axi_apb_bridge_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_axi_apb_bridge_0_1 || ORIG_REF_NAME==week10_axi_apb_bridge_0_1} -quiet] -quiet

# IP: bd/week10/ip/week10_auto_pc_0/week10_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week10_auto_pc_0 || ORIG_REF_NAME==week10_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week10/week10.gen/sources_1/bd/week10/week10_ooc.xdc
