# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/week5.xdc

# Block Designs: bd/week5/week5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5 || ORIG_REF_NAME==week5} -quiet] -quiet

# IP: bd/week5/ip/week5_processing_system7_0_0/week5_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_processing_system7_0_0 || ORIG_REF_NAME==week5_processing_system7_0_0} -quiet] -quiet

# IP: bd/week5/ip/week5_axi_gpio_0_0/week5_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_axi_gpio_0_0 || ORIG_REF_NAME==week5_axi_gpio_0_0} -quiet] -quiet

# IP: bd/week5/ip/week5_ps7_0_axi_periph_0/week5_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_ps7_0_axi_periph_0 || ORIG_REF_NAME==week5_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/week5/ip/week5_rst_ps7_0_100M_0/week5_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_rst_ps7_0_100M_0 || ORIG_REF_NAME==week5_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/week5/ip/week5_PWM_gen_8bit_0_0/week5_PWM_gen_8bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_PWM_gen_8bit_0_0 || ORIG_REF_NAME==week5_PWM_gen_8bit_0_0} -quiet] -quiet

# IP: bd/week5/ip/week5_auto_pc_0/week5_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week5_auto_pc_0 || ORIG_REF_NAME==week5_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week5/week5.gen/sources_1/bd/week5/week5_ooc.xdc
