# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Final_Project.xdc

# Block Designs: bd/Final_Project/Final_Project.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project || ORIG_REF_NAME==Final_Project} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_processing_system7_0_0/Final_Project_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_processing_system7_0_0 || ORIG_REF_NAME==Final_Project_processing_system7_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_xbar_0/Final_Project_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_xbar_0 || ORIG_REF_NAME==Final_Project_xbar_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_ps7_0_axi_periph_0/Final_Project_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_ps7_0_axi_periph_0 || ORIG_REF_NAME==Final_Project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_rst_ps7_0_100M_0/Final_Project_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_rst_ps7_0_100M_0 || ORIG_REF_NAME==Final_Project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_gpio_0_0/Final_Project_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_gpio_0_0 || ORIG_REF_NAME==Final_Project_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_gpio_1_0/Final_Project_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_gpio_1_0 || ORIG_REF_NAME==Final_Project_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_sevenseg_mux_0_0/Final_Project_sevenseg_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_sevenseg_mux_0_0 || ORIG_REF_NAME==Final_Project_sevenseg_mux_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_imu_i2c_mode_pins_0_0/Final_Project_imu_i2c_mode_pins_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_imu_i2c_mode_pins_0_0 || ORIG_REF_NAME==Final_Project_imu_i2c_mode_pins_0_0} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_apb_i2c_master_0_1/Final_Project_apb_i2c_master_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_apb_i2c_master_0_1 || ORIG_REF_NAME==Final_Project_apb_i2c_master_0_1} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_axi_apb_bridge_0_2/Final_Project_axi_apb_bridge_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_axi_apb_bridge_0_2 || ORIG_REF_NAME==Final_Project_axi_apb_bridge_0_2} -quiet] -quiet

# IP: bd/Final_Project/ip/Final_Project_auto_pc_0/Final_Project_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_Project_auto_pc_0 || ORIG_REF_NAME==Final_Project_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/Final_Project/Final_Project.gen/sources_1/bd/Final_Project/Final_Project_ooc.xdc
