# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/GPIO3/GPIO3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3 || ORIG_REF_NAME==GPIO3} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_processing_system7_0_0/GPIO3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_processing_system7_0_0 || ORIG_REF_NAME==GPIO3_processing_system7_0_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_axi_gpio_0_0/GPIO3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_axi_gpio_0_0 || ORIG_REF_NAME==GPIO3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_axi_gpio_1_0/GPIO3_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_axi_gpio_1_0 || ORIG_REF_NAME==GPIO3_axi_gpio_1_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_xbar_0/GPIO3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_xbar_0 || ORIG_REF_NAME==GPIO3_xbar_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_ps7_0_axi_periph_0/GPIO3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_ps7_0_axi_periph_0 || ORIG_REF_NAME==GPIO3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_rst_ps7_0_100M_0/GPIO3_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_rst_ps7_0_100M_0 || ORIG_REF_NAME==GPIO3_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_axi_gpio_2_0/GPIO3_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_axi_gpio_2_0 || ORIG_REF_NAME==GPIO3_axi_gpio_2_0} -quiet] -quiet

# IP: bd/GPIO3/ip/GPIO3_auto_pc_0/GPIO3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==GPIO3_auto_pc_0 || ORIG_REF_NAME==GPIO3_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week4/week4.gen/sources_1/bd/GPIO3/GPIO3_ooc.xdc
