# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/week3/week3.srcs/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0.xci
# IP: The module: 'PS_Block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/week3/week3.srcs/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0.xci
# IP: The module: 'PS_Block_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week3/week3.gen/sources_1/bd/PS_Block/ip/PS_Block_axi_gpio_0_0/PS_Block_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_Block_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
