# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/week11/week11.srcs/sources_1/bd/week11/ip/week11_processing_system7_0_1/week11_processing_system7_0_1.xci
# IP: The module: 'week11_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week11/week11.gen/sources_1/bd/week11/ip/week11_processing_system7_0_1/week11_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'week11_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/week11/week11.srcs/sources_1/bd/week11/ip/week11_processing_system7_0_1/week11_processing_system7_0_1.xci
# IP: The module: 'week11_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week11/week11.gen/sources_1/bd/week11/ip/week11_processing_system7_0_1/week11_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'week11_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
