# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/week9.xdc

# Block Designs: bd/week9/week9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9 || ORIG_REF_NAME==week9} -quiet] -quiet

# IP: bd/week9/ip/week9_processing_system7_0_0/week9_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9_processing_system7_0_0 || ORIG_REF_NAME==week9_processing_system7_0_0} -quiet] -quiet

# IP: bd/week9/ip/week9_ps7_0_axi_periph_0/week9_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9_ps7_0_axi_periph_0 || ORIG_REF_NAME==week9_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/week9/ip/week9_rst_ps7_0_100M_0/week9_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9_rst_ps7_0_100M_0 || ORIG_REF_NAME==week9_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/week9/ip/week9_axi_apb_bridge_0_0/week9_axi_apb_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9_axi_apb_bridge_0_0 || ORIG_REF_NAME==week9_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/week9/ip/week9_auto_pc_0/week9_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week9_auto_pc_0 || ORIG_REF_NAME==week9_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week9/week8.gen/sources_1/bd/week9/week9_ooc.xdc
