# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/week11.xdc

# Block Designs: bd/week11/week11.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11 || ORIG_REF_NAME==week11} -quiet] -quiet

# IP: bd/week11/ip/week11_processing_system7_0_1/week11_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11_processing_system7_0_1 || ORIG_REF_NAME==week11_processing_system7_0_1} -quiet] -quiet

# IP: bd/week11/ip/week11_axi_apb_bridge_0_2/week11_axi_apb_bridge_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11_axi_apb_bridge_0_2 || ORIG_REF_NAME==week11_axi_apb_bridge_0_2} -quiet] -quiet

# IP: bd/week11/ip/week11_ps7_0_axi_periph_0/week11_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11_ps7_0_axi_periph_0 || ORIG_REF_NAME==week11_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/week11/ip/week11_rst_ps7_0_100M_0/week11_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11_rst_ps7_0_100M_0 || ORIG_REF_NAME==week11_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/week11/ip/week11_auto_pc_0/week11_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==week11_auto_pc_0 || ORIG_REF_NAME==week11_auto_pc_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week11/week11.gen/sources_1/bd/week11/week11_ooc.xdc
