# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/middle_project/middle_project.srcs/sources_1/bd/middle_project/ip/middle_project_auto_pc_0/middle_project_auto_pc_0.xci
# IP: The module: 'middle_project_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/middle_project/middle_project.gen/sources_1/bd/middle_project/ip/middle_project_auto_pc_0/middle_project_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'middle_project_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/middle_project/middle_project.srcs/sources_1/bd/middle_project/ip/middle_project_auto_pc_0/middle_project_auto_pc_0.xci
# IP: The module: 'middle_project_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/middle_project/middle_project.gen/sources_1/bd/middle_project/ip/middle_project_auto_pc_0/middle_project_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'middle_project_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
