# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Tukorea/Digital_System_Project/week2/week2.srcs/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/zynq_sys_processing_system7_0_0.xci
# IP: The module: 'zynq_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week2/week2.gen/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/zynq_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Tukorea/Digital_System_Project/week2/week2.srcs/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/zynq_sys_processing_system7_0_0.xci
# IP: The module: 'zynq_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Tukorea/Digital_System_Project/week2/week2.gen/sources_1/bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/zynq_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
