# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_sys/zynq_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_sys || ORIG_REF_NAME==zynq_sys} -quiet] -quiet

# IP: bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/zynq_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_sys_processing_system7_0_0 || ORIG_REF_NAME==zynq_sys_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Tukorea/Digital_System_Project/week2/week2.gen/sources_1/bd/zynq_sys/zynq_sys_ooc.xdc
